"use client";
import { useState } from "react";

const reports = [
  {id:"1",title:"Monthly HR Summary - December 2024",desc:"Complete HR metrics including headcount, attrition, performance, and leave analytics for December",type:"PDF",size:"2.4 MB",date:"Dec 1, 2024",icon:"📊",category:"monthly",pages:24},
  {id:"2",title:"Q4 Performance Report 2024",desc:"Quarterly performance analysis across all departments with trend comparisons and recommendations",type:"Excel",size:"1.8 MB",date:"Oct 1, 2024",icon:"📈",category:"quarterly",sheets:8},
  {id:"3",title:"Attrition Risk Analysis - AI Report",desc:"Machine learning powered attrition predictions with individual risk scores and retention strategies",type:"PDF",size:"890 KB",date:"Dec 7, 2024",icon:"🔮",category:"ai",pages:12},
  {id:"4",title:"Salary Benchmarking Report 2024",desc:"Market salary comparison across roles, departments, and geographies with gap analysis",type:"Excel",size:"3.1 MB",date:"Nov 15, 2024",icon:"💰",category:"annual",sheets:12},
  {id:"5",title:"Training & Development Report",desc:"Learning completion rates, certification status, skill gap analysis and L&D ROI metrics",type:"PDF",size:"1.2 MB",date:"Nov 30, 2024",icon:"📚",category:"monthly",pages:18},
  {id:"6",title:"2025 Headcount Planning",desc:"AI-driven headcount forecast with department-wise budget projections for next fiscal year",type:"Excel",size:"956 KB",date:"Dec 5, 2024",icon:"👥",category:"ai",sheets:6},
  {id:"7",title:"Diversity & Inclusion Report",desc:"DEI metrics, gender pay gap analysis, inclusion index scores and improvement roadmap",type:"PDF",size:"1.5 MB",date:"Nov 20, 2024",icon:"🌍",category:"quarterly",pages:20},
  {id:"8",title:"Annual Compliance Report 2024",desc:"HR compliance checklist, audit findings, regulatory adherence status and action items",type:"PDF",size:"2.1 MB",date:"Dec 1, 2024",icon:"✅",category:"annual",pages:32},
];

export default function ReportsPage() {
  const [filter, setFilter] = useState("all");
  const [generating, setGenerating] = useState(false);
  const [downloading, setDownloading] = useState(null);
  const [generated, setGenerated] = useState(false);
  const filtered = filter === "all" ? reports : reports.filter(r => r.category === filter || r.type.toLowerCase() === filter);

  const handleGenerate = async () => {
    setGenerating(true);
    await new Promise(r => setTimeout(r, 2000));
    setGenerating(false);
    setGenerated(true);
    setTimeout(() => setGenerated(false), 4000);
  };

  const handleDownload = async (report) => {
    setDownloading(report.id);
    await new Promise(r => setTimeout(r, 1500));

    if (report.type === "PDF") {
      const content = `PulseHR Report
${report.title}
Generated: ${new Date().toLocaleDateString()}
Size: ${report.size}

${report.desc}

This is a demo PDF report from PulseHR HR Analytics Platform.
In production, this would contain full HR analytics data.

Key Metrics:
- Total Employees: 2,847
- Avg Performance: 78.4%
- Attrition Risk: 143 high-risk employees
- Goals Completed: 89%

Generated by PulseHR AI-Powered HR Platform`;

      const blob = new Blob([content], {type:"text/plain"});
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${report.title.replace(/[^a-z0-9]/gi,"_")}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } else {
      const csvContent = [
        ["Metric","Value","Department","Period"],
        ["Total Employees","2847","All","Q4 2024"],
        ["Avg Performance","78.4%","All","Q4 2024"],
        ["Attrition Risk","143","All","Q4 2024"],
        ["Goals Completed","89%","All","Q4 2024"],
        ["Engineering Score","82%","Engineering","Q4 2024"],
        ["Sales Score","91%","Sales","Q4 2024"],
        ["Design Score","84%","Design","Q4 2024"],
        ["HR Score","79%","HR","Q4 2024"],
        ["Finance Score","88%","Finance","Q4 2024"],
        ["Leave Taken","1240 days","All","Q4 2024"],
        ["New Hires","67","All","Q4 2024"],
        ["Exits","19","All","Q4 2024"],
      ].map(row => row.join(",")).join("\n");

      const blob = new Blob([csvContent], {type:"text/csv"});
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${report.title.replace(/[^a-z0-9]/gi,"_")}.csv`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }

    setDownloading(null);
  };

  return (
    <div style={{display:"flex",flexDirection:"column",gap:"24px"}}>
      {generated && (
        <div style={{background:"rgba(34,197,94,0.1)",border:"1px solid rgba(34,197,94,0.3)",borderRadius:"12px",padding:"14px 20px",color:"#22c55e",display:"flex",alignItems:"center",gap:"10px"}}>
          ✅ New report generated successfully! It will appear in the list below.
        </div>
      )}

      <div style={{display:"flex",justifyContent:"space-between",alignItems:"start",flexWrap:"wrap",gap:"16px"}}>
        <div>
          <h1 style={{fontFamily:"Instrument Serif,serif",fontSize:"2rem",color:"hsl(var(--foreground))"}}>Reports</h1>
          <p style={{color:"hsl(var(--muted-foreground))",fontSize:"0.875rem",marginTop:"4px"}}>Download, generate and export HR reports</p>
        </div>
        <button onClick={handleGenerate} disabled={generating} style={{background:generating?"rgba(255,255,255,0.05)":"rgba(59,130,246,0.15)",border:`1px solid ${generating?"rgba(255,255,255,0.08)":"rgba(59,130,246,0.3)"}`,borderRadius:"10px",padding:"11px 20px",color:generating?"hsl(var(--muted-foreground))":"#3b82f6",cursor:generating?"not-allowed":"pointer",fontSize:"0.875rem",fontWeight:500,display:"flex",alignItems:"center",gap:"8px"}}>
          {generating ? <><span style={{display:"inline-block",width:"14px",height:"14px",border:"2px solid rgba(59,130,246,0.3)",borderTopColor:"#3b82f6",borderRadius:"50%",animation:"spin 0.8s linear infinite"}}/> Generating...</> : "⚡ Generate New Report"}
        </button>
      </div>

      <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:"12px"}}>
        {[["Total Reports",reports.length,"📁","#3b82f6"],["PDF Reports",reports.filter(r=>r.type==="PDF").length,"📄","#ef4444"],["Excel Reports",reports.filter(r=>r.type==="Excel").length,"📊","#22c55e"],["AI Reports",reports.filter(r=>r.category==="ai").length,"🤖","#8b5cf6"]].map(([label,val,icon,color]) => (
          <div key={label} style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"12px",padding:"16px",textAlign:"center"}}>
            <div style={{fontSize:"1.25rem",marginBottom:"4px"}}>{icon}</div>
            <div style={{fontSize:"1.5rem",fontFamily:"Instrument Serif,serif",color}}>{val}</div>
            <div style={{fontSize:"0.7rem",color:"hsl(var(--muted-foreground))",marginTop:"2px"}}>{label}</div>
          </div>
        ))}
      </div>

      <div style={{display:"flex",gap:"8px",flexWrap:"wrap"}}>
        {["all","monthly","quarterly","annual","ai","pdf","excel"].map(f => (
          <button key={f} onClick={() => setFilter(f)} style={{padding:"7px 16px",fontSize:"0.8rem",borderRadius:"8px",border:"none",cursor:"pointer",textTransform:"capitalize",background:filter===f?"hsl(var(--foreground))":"rgba(255,255,255,0.05)",color:filter===f?"hsl(var(--background))":"hsl(var(--muted-foreground))",transition:"all 0.2s"}}>{f}</button>
        ))}
      </div>

      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(320px,1fr))",gap:"16px"}}>
        {filtered.map(report => (
          <div key={report.id} style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"16px",padding:"20px",transition:"all 0.2s",display:"flex",flexDirection:"column"}} onMouseEnter={e=>{e.currentTarget.style.transform="translateY(-2px)";e.currentTarget.style.borderColor="rgba(255,255,255,0.15)"}} onMouseLeave={e=>{e.currentTarget.style.transform="translateY(0)";e.currentTarget.style.borderColor="rgba(255,255,255,0.08)"}}>
            <div style={{fontSize:"2rem",marginBottom:"12px"}}>{report.icon}</div>
            <h3 style={{fontSize:"0.9rem",fontWeight:500,color:"hsl(var(--foreground))",marginBottom:"6px",lineHeight:"1.4"}}>{report.title}</h3>
            <p style={{fontSize:"0.75rem",color:"hsl(var(--muted-foreground))",marginBottom:"16px",lineHeight:"1.5",flex:1}}>{report.desc}</p>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"12px"}}>
              <div style={{display:"flex",gap:"8px",alignItems:"center"}}>
                <span style={{fontSize:"0.7rem",padding:"3px 8px",borderRadius:"6px",background:report.type==="PDF"?"rgba(239,68,68,0.1)":"rgba(34,197,94,0.1)",color:report.type==="PDF"?"#ef4444":"#22c55e",fontWeight:600}}>{report.type}</span>
                <span style={{fontSize:"0.7rem",color:"hsl(var(--muted-foreground))"}}>{report.size}</span>
                {report.pages && <span style={{fontSize:"0.7rem",color:"hsl(var(--muted-foreground))"}}>· {report.pages} pages</span>}
                {report.sheets && <span style={{fontSize:"0.7rem",color:"hsl(var(--muted-foreground))"}}>· {report.sheets} sheets</span>}
              </div>
            </div>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>
              <span style={{fontSize:"0.7rem",color:"hsl(var(--muted-foreground))"}}>{report.date}</span>
              <button onClick={() => handleDownload(report)} disabled={downloading===report.id} style={{fontSize:"0.8rem",background:downloading===report.id?"rgba(255,255,255,0.03)":"rgba(59,130,246,0.1)",border:`1px solid ${downloading===report.id?"rgba(255,255,255,0.05)":"rgba(59,130,246,0.2)"}`,borderRadius:"8px",padding:"6px 14px",color:downloading===report.id?"hsl(var(--muted-foreground))":"#3b82f6",cursor:downloading===report.id?"not-allowed":"pointer",display:"flex",alignItems:"center",gap:"6px",transition:"all 0.2s"}}>
                {downloading===report.id ? <><span style={{display:"inline-block",width:"10px",height:"10px",border:"2px solid rgba(59,130,246,0.3)",borderTopColor:"#3b82f6",borderRadius:"50%",animation:"spin 0.8s linear infinite"}}/> Downloading...</> : "↓ Download"}
              </button>
            </div>
          </div>
        ))}
      </div>
      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
    </div>
  );
}
